; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:attiny85]
platform = atmelavr
board = attiny85
framework = arduino

build_flags = -DF_CPU=8000000L
board_fuses.lfuse = 0b01100001 ; program CKDIV8 fuse
; board_fuses.hfuse = 0b11011111 ; default Fuse High Byte (see datasheet p148)
board_fuses.hfuse = 0b11011110 ; enable brown-out detection around 1.8V (see datasheet p148 and p166)
; board_fuses.hfuse = 0b11011101 ; enable brown-out detection around 2.7V (see datasheet p148 and p166)
board_fuses.efuse = 0xFF

; Use Arduino Uno running ArduinoISP
;upload_protocol = custom
upload_command = avrdude -C${platformio.packages_dir}/tool-avrdude/avrdude.conf -p t85 -c stk500v1 -P /dev/ttyUSB0 -b 19200 -U flash:w:.pio/build/attiny85/firmware.hex:i
; use ArduinoISP programmer running on Arduino Uno
upload_protocol = custom
upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p 
    t85
    -c
    stk500v1
    -P
    /dev/ttyUSB0
    -b
    19200
    -v
